# Generated by Django 4.0.2 on 2022-05-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='mshop',
            name='phone',
            field=models.CharField(default='12345566', max_length=12),
            preserve_default=False,
        ),
    ]
